export enum ActionType {
  ADD_CATEGORY = "ADD_CATEGORY",
  REMOVE_CATEGORY = "REMOVE_CATEGORY",
  GET_CATEGORY = "GET_CATEGORY",
  GET_ITEMS = "GET_ITEMS",
  ADD_ITEM = "ADD_ITEM",
  REMOVE_ITEM = "REMOVE_ITEM",
  REMOVE_CATEGORY_ITEMS = "REMOVE_CATEGORY_ITEMS",
  GET_INCOME_BY_CATEGORY = "GET_INCOME_BY_CATEGORY",
  GET_EXPENSE_BY_CATEGORY = "GET_EXPENSE_BY_CATEGORY",
}
